//# Se destruyen todas las tablas previo a su creación
DROP TABLE DOMICILIOS IF EXISTS;
DROP TABLE PACIENTES IF EXISTS;
DROP TABLE ODONTOLOGOS IF EXISTS;

//# Tabla DOMICILIOS (del paciente)
CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(50) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL
);

//# Tabla PACIENTES
CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DNI VARCHAR(10) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ID_DOMICILIO INT NOT NULL
);

//# Tabla ODONTOLOGOS
CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
nroMatricula VARCHAR(50) NOT NULL,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL
);

//# Inserta registros en DOMICILIOS y PACIENTES
INSERT INTO DOMICILIOS VALUES (DEFAULT,'Calle SIEMPRE VIVA', 12345, 'SAN Miguel', 'JUJUY');
INSERT INTO PACIENTES VALUES (DEFAULT, 'Maradona', 'Diego Armando', '1234567890', '2024-08-15',1);

//# Inserta registros en ODONTOLOGOS
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, '12345', 'Marcela', 'Rendón');
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, '2456', 'Juan', 'Roldán');